<?php

namespace App\OpenApi;

/**
 * API path items for Swagger.
 *
 * @OA\PathItem(path="/auth/login", post=@OA\Post(tags={"Auth"}, summary="Login", operationId="login", requestBody=@OA\RequestBody(required=true, content=@OA\JsonContent(required={"email","password"}, properties={@OA\Property(property="email", type="string", example="user@example.com"), @OA\Property(property="password", type="string", example="password")})), responses={@OA\Response(response=200, description="Returns user and access_token")}))
 * @OA\PathItem(path="/auth/register", post=@OA\Post(tags={"Auth"}, summary="Register", operationId="register", requestBody=@OA\RequestBody(required=true, content=@OA\JsonContent(required={"name","email","password","password_confirmation"}, properties={@OA\Property(property="name", type="string"), @OA\Property(property="email", type="string"), @OA\Property(property="password", type="string"), @OA\Property(property="password_confirmation", type="string")})), responses={@OA\Response(response=201, description="Created")}))
 * @OA\PathItem(path="/auth/refresh", post=@OA\Post(tags={"Auth"}, summary="Refresh JWT", operationId="refresh", responses={@OA\Response(response=200, description="New token")}))
 * @OA\PathItem(path="/auth/me", get=@OA\Get(tags={"Auth"}, summary="Current user", operationId="me", responses={@OA\Response(response=200, description="User with agents")}))
 * @OA\PathItem(path="/auth/logout", post=@OA\Post(tags={"Auth"}, summary="Logout", operationId="logout", responses={@OA\Response(response=200, description="OK")}))
 * @OA\PathItem(path="/agents", get=@OA\Get(tags={"Agents"}, summary="List agents", operationId="agentsIndex", responses={@OA\Response(response=200, description="List of agents")}), post=@OA\Post(tags={"Agents"}, summary="Create agent (Admin)", operationId="agentsStore", requestBody=@OA\RequestBody(content=@OA\JsonContent(properties={@OA\Property(property="name", type="string"), @OA\Property(property="allowed_users", type="string")})), responses={@OA\Response(response=201, description="Created")}))
 * @OA\PathItem(path="/agents/user-agents", get=@OA\Get(tags={"Agents"}, summary="User agents for dropdown", operationId="userAgents", responses={@OA\Response(response=200, description="List")}))
 * @OA\PathItem(path="/transactions", get=@OA\Get(tags={"Transactions"}, summary="List transactions", operationId="transactionsIndex", parameters={@OA\Parameter(in="query", name="agent_id", @OA\Schema(type="integer")), @OA\Parameter(in="query", name="status", @OA\Schema(type="string")), @OA\Parameter(in="query", name="date_from", @OA\Schema(type="string")), @OA\Parameter(in="query", name="date_to", @OA\Schema(type="string")), @OA\Parameter(in="query", name="per_page", @OA\Schema(type="integer"))}, responses={@OA\Response(response=200, description="Paginated list")}), post=@OA\Post(tags={"Transactions"}, summary="Create transaction", operationId="transactionsStore", requestBody=@OA\RequestBody(required=true, content=@OA\JsonContent(required={"agent_id","total_amount","transaction_type"}, properties={@OA\Property(property="agent_id", type="integer"), @OA\Property(property="customer_name", type="string"), @OA\Property(property="cccd_number", type="string"), @OA\Property(property="total_amount", type="number"), @OA\Property(property="transaction_type", type="string", enum={"Đáo","Rút"}), @OA\Property(property="pos_fee_percent", type="number"), @OA\Property(property="agent_fee_percent", type="number"), @OA\Property(property="agent_advance", type="number")})), responses={@OA\Response(response=201, description="Created")}))
 * @OA\PathItem(path="/statistics", get=@OA\Get(tags={"Statistics"}, summary="Statistics by agent (completed only)", operationId="statisticsIndex", parameters={@OA\Parameter(in="query", name="agent_id", required=true, @OA\Schema(type="integer")), @OA\Parameter(in="query", name="period", @OA\Schema(type="string", enum={"all","today","3days","week","month"}))}, responses={@OA\Response(response=200, description="Totals, dao_count, rut_count, recent, by_status")}))
 * @OA\PathItem(path="/settlements/eod", get=@OA\Get(tags={"Settlements"}, summary="EOD settlement data", operationId="getEod", parameters={@OA\Parameter(in="query", name="agent_id", required=true, @OA\Schema(type="integer")), @OA\Parameter(in="query", name="date", required=true, @OA\Schema(type="string", description="dd/mm/yyyy"))}, responses={@OA\Response(response=200, description="Totals and transactions")}))
 * @OA\PathItem(path="/daily-advances", get=@OA\Get(tags={"Settlements"}, summary="Daily advance summary", operationId="getDailyAdvances", parameters={@OA\Parameter(in="query", name="agent_id", required=true, @OA\Schema(type="integer")), @OA\Parameter(in="query", name="date", required=true, @OA\Schema(type="string"))}, responses={@OA\Response(response=200, description="total_advance, transactions")}))
 * @OA\PathItem(path="/momo/generate-qr", post=@OA\Post(tags={"MoMo"}, summary="Generate MoMo QR", operationId="momoGenerateQr", requestBody=@OA\RequestBody(required=true, content=@OA\JsonContent(required={"customer_name","total_amount","transaction_type"}, properties={@OA\Property(property="customer_name", type="string"), @OA\Property(property="total_amount", type="number"), @OA\Property(property="transaction_type", type="string", enum={"Đáo","Rút"})})), responses={@OA\Response(response=200, description="qrCodeUrl, payUrl, deeplink")}))
 * @OA\PathItem(path="/config", get=@OA\Get(tags={"Config"}, summary="App config", operationId="config", responses={@OA\Response(response=200, description="version, fees, status_values, amount_suggestions")}))
 */
class ApiPaths
{
}
